Repository democracyworks/ColoradoRLA, pull requests merged in 2019-02, with the labels that each got.

#117 Add ballot re-auditing feature
  client/action.d.ts
  client/county.d.ts
  client/json.d.ts
  client/npm-shrinkwrap.json
  client/package.json
  client/screen.css
  client/src/action/county/ballotNotFound.ts
  client/src/action/county/reAuditCvr.ts
  client/src/action/county/uploadAcvr.ts
  client/src/adapter/uploadAcvr.ts
  client/src/component/County/Audit/EndOfRound/FinalReviewDialog.tsx
  client/src/component/County/Audit/EndOfRound/FinalReviewPage.tsx
  client/src/component/County/Audit/EndOfRound/FinalReviewPageContainer.tsx
  client/src/component/County/Audit/EndOfRound/Page.tsx
  client/src/component/County/Audit/EndOfRound/PageContainer.tsx
  client/src/component/County/Audit/Page.tsx
  client/src/component/County/Audit/PageContainer.tsx
  client/src/component/County/Audit/Wizard/BallotAuditStage.tsx
  client/src/component/County/Audit/Wizard/BallotAuditStageContainer.tsx
  client/src/component/County/Audit/Wizard/Container.tsx
  client/src/component/County/Audit/Wizard/ReviewStage.tsx
  client/src/component/County/Audit/Wizard/ReviewStageContainer.tsx
  client/src/component/County/Audit/Wizard/Wizard.tsx
  client/src/component/County/AuditBoard/Page.tsx
  client/src/component/County/AuditBoard/PageContainer.tsx
  client/src/component/County/AuditBoard/SignedInPage.tsx
  client/src/component/County/Dashboard/BallotManifest/Form.tsx
  client/src/component/County/Dashboard/CVRExport/Form.tsx
  client/src/component/County/Dashboard/Main.tsx
  client/src/component/County/Dashboard/PageContainer.tsx
  client/src/component/NavMenu.tsx
  client/src/reducer/county/dashboardRefreshOk.ts
  client/src/reducer/county/fetchCvrOk.ts
  client/src/reducer/county/reAuditCvr.ts
  client/src/reducer/defaultState.ts
  client/src/reducer/root.ts
  client/src/saga/county/acvrUploadSaga.ts
  client/src/saga/county/dashboardRefreshOkSaga.ts
  client/src/saga/county/reAuditCvrSaga.ts
  client/src/saga/county/uploadAcvrOkSaga.ts
  client/src/saga/root.ts
  client/src/selector/county/canAudit.ts
  client/src/selector/county/currentBallotNumber.ts
  client/src/selector/county/totalBallotsForBoard.ts
  server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java
  server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/ACVRUpload.java
  server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/BallotNotFound.java
  server/eclipse-project/src/main/java/us/freeandfair/corla/json/SubmittedAuditCVR.java
  server/eclipse-project/src/main/java/us/freeandfair/corla/json/SubmittedBallotNotFound.java
  server/eclipse-project/src/main/java/us/freeandfair/corla/model/CastVoteRecord.java
  server/eclipse-project/src/main/java/us/freeandfair/corla/model/ComparisonAudit.java
  server/eclipse-project/src/main/java/us/freeandfair/corla/query/CastVoteRecordQueries.java
  server/eclipse-project/src/test/java/us/freeandfair/corla/query/CastVoteRecordQueriesTest.java
  test/load/genrun.sh
Labels: area/api, area/ui

#118 Fix sorting to accommodate numeric strings naturally
  client/src/component/DOS/Dashboard/ContestUpdates.tsx
  client/src/component/DOS/Dashboard/CountyUpdates.tsx
  client/src/component/DOS/DefineAudit/SelectContestsForm.tsx
  client/src/util.ts
Labels: area/ui

#119 Contest name suggestion
  client/dos.d.ts
  client/npm-shrinkwrap.json
  client/package.json
  client/src/adapter/standardizeContests.ts
  client/src/component/DOS/DefineAudit/StandardizeContestsPage.tsx
  client/src/component/DOS/DefineAudit/StandardizeContestsPageContainer.tsx
  client/vendor.d.ts
Labels: area/ui

#122 [api] reaudit fix - cdb discrepancy count
  server/eclipse-project/src/main/java/us/freeandfair/corla/controller/ComparisonAuditController.java
Labels: area/api
